name: "Bug report (with logs)"
description: "Report a bug and attach your ImageToPose logs"
title: "[bug]: <short summary>"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Thank you!** Please attach log files from:

        **Application Logs:**
        - `%LOCALAPPDATA%\Temp\ImageToPose\logs`
        - e.g. `C:\Users\<your_name>\AppData\Local\Temp\ImageToPose\logs`

        **AI Diagnostics Logs (if the issue involves AI/model errors):**
        - `%LOCALAPPDATA%\ImageToPose\logs\ai_diagnostics`
        - e.g. `C:\Users\<your_name>\AppData\Local\ImageToPose\logs\ai_diagnostics\<date>\<timestamp>.json`

        👉 Drag & drop the file(s) into the issue editor **below** before submitting.
        If files are large, please ZIP them first.

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      options:
        - label: I searched existing issues and couldn't find this.
          required: true
        - label: I **attached** at least one application log file from the folder above.
          required: true
        - label: I **attached** AI diagnostics logs (if the issue involves model/AI errors).
          required: false

  - type: input
    id: app-version
    attributes:
      label: App version / build
      description: e.g., app About box version or commit SHA
      placeholder: "v0.5.1 (commit abc1234)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Windows 11
        - Windows 10
        - Other
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Be as precise as possible (what you clicked, expected vs. actual).
      placeholder: |
        1. …
        2. …
        3. …
    validations:
      required: true

  - type: textarea
    id: log-snippet
    attributes:
      label: Optional — paste last ~100 lines of the application log
      description: This helps even if the attachment fails. For AI diagnostics, you can paste the full JSON content.
      render: text
      placeholder: |
        (Open the latest .log or .json in a text editor and copy the tail here)
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context / screenshots
      description: You can drag & drop images or more files here.
      render: text
