blank_issues_enabled: false
contact_links:
  - name: Q&A / Discussions
    url: https://github.com/AlexRynas/Image_To_Pose_Generator/discussions
    about: Ask questions or share ideas here rather than opening an issue.
